Market/Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('products/', include("products.urls")),
    path('users/', include("users.urls")),
    path('cart/', include("cart.urls")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

Market/cart/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('increase_item/<int:product_id>/', views.add_to_cart, name='increase_item'),
    path('decrease_item/<int:product_id>/', views.decrease_item, name='decrease_item'),
    path('remove_from_cart/<int:product_id>/', views.delete_item, name='remove_from_cart'),
]

Market/products/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>', views.product_instance, name='product_instance'),
    path('product_filter/<int:type_pk>', views.filter_type, name='product_filter'),
]

Market/products/models.py
from django.db import models
from django.urls import reverse


class Type(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return f"title: {self.title}, id: {self.pk}"


class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    count = models.PositiveIntegerField()
    descriptions = models.TextField()
    product_type = models.ForeignKey(Type, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return f"title: {self.title}, id: {self.pk}"

    def get_absolute_url(self):
        return reverse("product_instance", kwargs={"pk": self.pk})


class ProductIMG(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/')

Market/products/views.py
from django.shortcuts import render

from .models import Product, Type

type_list = Type.objects.all()


def product_list(requests):
    products = Product.objects.all()
    return render(requests, "products/product_list.html", context={"products": products, "product_type": type_list})


def product_instance(requests, pk):
    product = Product.objects.get(pk=pk)
    return render(requests, "products/product_instance.html", context={"product": product})


def filter_type(requests, type_pk):
    products = Product.objects.filter(product_type=type_pk)
    return render(requests, "products/product_list.html", context={"products": products, "product_type": type_list})

Market/products/templates/products/product_instance.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/product_instance.css' %}">
{%endblock %}
{% block main %}
<section class = "product container">
  <div class="product_wrapper">
    <div class="img_wrapper">
      <img src="{{product.productimg_set.first.image.url}}" alt="" class="product_img">
    </div>
    <div class="product_information">
      <h2 class="product_title">
        {{product.title}}
      </h2>
      <p class="product_price">
        {{product.price}}
      </p>
      <a href="{%url 'add_to_cart' product.pk%}" class="add_to_cart">В корзину</a>
    </div>
  </div>
  <div class="product_details_wrapper">
    <h3 class="descriptions_title">Описание</h3>
    <p class="product_descriptions">
      {{product.descriptions}}
    </p>
  </div>
</section>
{%endblock%}

Market/products/templates/products/product_list.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/product_list.css' %}">
{%endblock %}
{% block main %}
<section class="container">
    <div class="catalog-wrapper">

        <div class="menu">
            <nav>
                <ul class="name_menu">
                    {%for type in product_type %}
                    <li><a class="link1" href="{%url 'product_filter' type.pk%}">{{type.title}}</a></li>
                    {%endfor%}
                </ul>
            </nav>
        </div>

        <div class="catalog">

            <h1 class="h1_container">МЕБЕЛЬ</h1>
            <ul class="product_list">
                {% for p in products %}

                <li class="product_item ">
                    <div class="product_img_container">
                        <img class="product_img" src="{{p.productimg_set.first.image.url}}">
                    </div>
                    <div class="product-nav">

                        <a href="{{p.get_absolute_url}}">
                            <h2 class="product_title">{{p.title}}</h2>
                        </a>
                        <p class="product_price">{{p.price}}</p>
                        <a href="{%url 'add_to_cart' p.pk%}" class="product_button">В корзину</a>

                    </div>
                </li>

                {% endfor %}
            </ul>

        </div>

    </div>
</section>

{% endblock %}